'use client';
import { useState } from 'react';

const tabs=['Collections','Publish','Offers','Auctions','Royalties','My Assets'];
export default function MarketplaceLayer(){
  const [tab,setTab]=useState('Collections');
  const [wallet,setWallet]=useState('');
  const [status,setStatus]=useState('');
  const [title,setTitle]=useState('');
  const [price,setPrice]=useState('');
  async function connect(){
    try{
      if(!window.ethereum){setStatus('Open Voxel Vault in MetaMask Mobile to connect.');return}
      const a=await window.ethereum.request({method:'eth_requestAccounts'});
      setWallet(a?.[0]||''); setStatus(a?.[0]?'Wallet connected.':'Connection cancelled.');
    }catch(e){setStatus(e?.message||'Wallet connection failed.')}
  }
  function action(text){setStatus(text)}
  return <section className="marketplaceLayer" id="marketplace"><div className="marketplaceInner">
    <div className="marketplaceHead"><div><div className="marketEyebrow">THE MARKETPLACE ENGINE</div><h2>From <em>asset</em> to ownership.</h2><p>Publish real 3D files, organize collections, mint ownership, and prepare secondary-market activity without changing the Voxel Vault visual language.</p></div><button className="marketWallet" onClick={connect}>{wallet?`${wallet.slice(0,6)}…${wallet.slice(-4)}`:'◈ Connect wallet'}</button></div>
    <div className="marketTabs">{tabs.map(t=><button key={t} className={tab===t?'marketTab active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
    {tab==='Collections'&&<div className="marketGrid"><div><span>COLLECTIONS</span><strong>Creator drops</strong><p>Group voxel models into branded collections with supply, rarity and creator metadata.</p><button onClick={()=>setTab('Publish')}>Publish a collection →</button></div><div><span>OWNERSHIP</span><strong>Wallet-native</strong><p>Connect MetaMask and keep the collector identity tied to the wallet that owns the asset.</p><button onClick={connect}>Connect wallet →</button></div><div><span>SECONDARY MARKET</span><strong>Offers + auctions</strong><p>Prepare fixed-price sales, offers and timed auctions for minted assets.</p><button onClick={()=>setTab('Offers')}>Open market →</button></div></div>}
    {tab==='Publish'&&<div className="publishPanel"><div><span>CREATOR PUBLISHING</span><strong>Publish a real 3D asset</strong><p>Upload the GLB/GLTF, attach metadata, choose a collection and set the primary price. The publishing surface is ready for the contract-backed mint flow.</p><div className="publishFields"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Asset name"/><input value={price} onChange={e=>setPrice(e.target.value)} placeholder="Primary price"/><input type="file" accept=".glb,.gltf,model/gltf-binary,model/gltf+json"/></div><button onClick={()=>action(title?`“${title}” is staged for minting.`:'Add an asset name first.')}>Stage for mint →</button></div><div className="publishChecklist"><b>01</b><span>3D file</span><b>02</b><span>Metadata</span><b>03</b><span>Collection</span><b>04</b><span>Mint + ownership</span></div></div>}
    {tab==='Offers'&&<div className="marketGrid"><div><span>OFFERS</span><strong>Make an offer</strong><p>Collectors can propose a price against a minted asset.</p><button onClick={()=>action('Offer flow is staged for the connected wallet.')}>Make offer →</button></div><div><span>LISTING</span><strong>Buy now</strong><p>Fixed-price listings route the collector into the wallet transaction flow.</p><button onClick={()=>action('Buy-now flow is ready for contract wiring.')}>Buy now →</button></div><div><span>OWNER</span><strong>Manage listings</strong><p>Owners can prepare price changes, delistings and transfers.</p><button onClick={()=>setTab('My Assets')}>My assets →</button></div></div>}
    {tab==='Auctions'&&<div className="marketGrid"><div><span>TIMED AUCTION</span><strong>Start an auction</strong><p>Set a reserve, duration and minimum bid for a minted asset.</p><button onClick={()=>action('Auction setup staged.')}>Start auction →</button></div><div><span>BIDDING</span><strong>Live bids</strong><p>Bid activity belongs to the wallet, not a username stored in the UI.</p><button onClick={()=>action('Bid flow staged for wallet transactions.')}>Place bid →</button></div></div>}
    {tab==='Royalties'&&<div className="royaltyPanel"><span>CREATOR ECONOMY</span><strong>Keep the creator in the loop.</strong><p>Each collection can carry creator royalty metadata for supported secondary-market sales. Configure the percentage at publish time and surface it clearly to collectors.</p><div className="royaltyBar"><label>Creator royalty</label><input type="range" min="0" max="15" defaultValue="5"/><b>5%</b></div></div>}
    {tab==='My Assets'&&<div className="marketGrid"><div><span>OWNED</span><strong>Wallet inventory</strong><p>Show minted assets owned by the connected wallet and open each in the 3D viewer.</p><button onClick={connect}>Sync wallet →</button></div><div><span>DOWNLOADS</span><strong>Game + VR files</strong><p>Owners can receive the downloadable GLB/GLTF package when the asset license permits it.</p><button onClick={()=>action('Download entitlement checked at checkout.')}>Check entitlement →</button></div><div><span>CREATOR</span><strong>Publish another</strong><p>Return to the creator pipeline and add another model to a collection.</p><button onClick={()=>setTab('Publish')}>Create asset →</button></div></div>}
    {status&&<div className="marketStatus">● {status}</div>}
  </div><style jsx>{` .marketplaceLayer{padding:20px 5vw 110px;background:#05060a}.marketplaceInner{max-width:1320px;margin:auto;border:1px solid #27233b;border-radius:24px;background:radial-gradient(circle at 85% 15%,rgba(113,77,255,.16),transparent 34%),linear-gradient(145deg,#0b0d14,#100e1c);padding:42px}.marketplaceHead{display:flex;justify-content:space-between;gap:30px;align-items:end}.marketEyebrow{font-size:9px;letter-spacing:2.5px;color:#8970ff;font-weight:900}.marketplaceHead h2{font-size:46px;letter-spacing:-2px;margin:10px 0}.marketplaceHead h2 em{font-style:normal;color:#987bff}.marketplaceHead p{max-width:680px;color:#858c9e;line-height:1.65}.marketWallet,.marketGrid button,.publishPanel button{border:1px solid #393251;background:#11121b;color:#fff;border-radius:10px;padding:12px 15px;font-weight:800;cursor:pointer}.marketTabs{display:flex;gap:7px;flex-wrap:wrap;margin:30px 0 18px;border-bottom:1px solid #222536;padding-bottom:12px}.marketTab{border:0;background:transparent;color:#6f7689;padding:10px 12px;border-radius:8px;cursor:pointer;font-size:10px}.marketTab.active{background:#1b1533;color:#fff}.marketGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.marketGrid>div,.publishPanel,.royaltyPanel{border:1px solid #25293a;background:#0a0c13;border-radius:15px;padding:24px}.marketGrid span,.publishPanel span,.royaltyPanel span{display:block;color:#8173b6;font-size:8px;letter-spacing:2px;margin-bottom:10px}.marketGrid strong,.publishPanel strong,.royaltyPanel strong{display:block;font-size:20px}.marketGrid p,.publishPanel p,.royaltyPanel p{color:#777f92;font-size:11px;line-height:1.7;min-height:55px}.publishPanel{display:grid;grid-template-columns:1fr 280px;gap:30px}.publishFields{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:20px 0}.publishFields input{background:#07080d;border:1px solid #2b3040;color:#fff;border-radius:9px;padding:12px}.publishFields input[type=file]{grid-column:1/-1}.publishChecklist{display:grid;grid-template-columns:38px 1fr;gap:14px;align-content:center}.publishChecklist b{color:#7659e9}.publishChecklist span{color:#a4aaba;margin:0}.royaltyBar{display:flex;align-items:center;gap:15px;margin-top:25px}.royaltyBar label{font-size:10px;color:#9299aa}.royaltyBar input{flex:1}.marketStatus{margin-top:18px;border:1px solid #34304b;background:#141225;border-radius:9px;padding:11px;color:#aaa4c9;font-size:10px}@media(max-width:800px){.marketplaceInner{padding:24px}.marketplaceHead{display:block}.marketWallet{margin-top:15px}.marketGrid,.publishPanel{grid-template-columns:1fr}.publishFields{grid-template-columns:1fr}}`}</style></section>
}
