'use client';

import { useEffect, useRef } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';

function mat(color, metal = 0.35, rough = 0.3) { return new THREE.MeshStandardMaterial({ color, metalness: metal, roughness: rough }); }
function add(g, geometry, material, p=[0,0,0], r=[0,0,0], s=[1,1,1]) { const m=new THREE.Mesh(geometry,material); m.position.set(...p); m.rotation.set(...r); m.scale.set(...s); m.castShadow=true; m.receiveShadow=true; g.add(m); return m; }
function buildProduct(item={}) {
  const g=new THREE.Group(); const name=`${item.name||''} ${item.type||''}`.toLowerCase();
  const main=mat(item.material==='gold'?0xd6a52d:item.material==='obsidian'?0x161922:item.material==='ceramic'?0xe8e2d7:0x9aa4b5,.78,.2); const dark=mat(0x11131a,.7,.2); const white=mat(0xf3f3f1,.05,.38); const glass=mat(0x8edcff,.1,.08);
  if(name.includes('headphone')) { add(g,new THREE.TorusGeometry(1.35,.13,16,64,Math.PI),main,[0,.45,0],[Math.PI/2,0,0]); for(const x of [-1.35,1.35]){add(g,new THREE.CylinderGeometry(.48,.48,.28,32),dark,[x,.1,0],[Math.PI/2,0,0]);add(g,new THREE.TorusGeometry(.4,.09,12,32),main,[x,.1,0],[Math.PI/2,0,0]);} }
  else if(name.includes('airpods')||name.includes('earbud')) { for(const x of [-.62,.62]){add(g,new THREE.SphereGeometry(.48,24,16),main,[x,.25,0],[0,0,0],[1,.65,1]);add(g,new THREE.CapsuleGeometry(.11,.55,8,12),main,[x,-.15,.08]);} add(g,new THREE.BoxGeometry(1.65,.9,1.05),main,[0,-.65,0],[0,0,0],[1,.7,.9]); }
  else if(name.includes('shoe')||name.includes('air force')) { add(g,new THREE.SphereGeometry(1,28,18),white,[0,-.05,0],[0,0,0],[2.5,.62,1.05]); add(g,new THREE.BoxGeometry(2.8,.28,1.12),white,[0,-.5,0]); for(let i=0;i<5;i++) add(g,new THREE.CylinderGeometry(.025,.025,.7,10),dark,[-.65+i*.32,.18,-.53],[Math.PI/2,0,0]); }
  else if(name.includes('iphone')||name.includes('phone')) { add(g,new THREE.BoxGeometry(1.45,2.8,.18),main,[0,0,0],[0,.08,0]); add(g,new THREE.BoxGeometry(1.23,2.5,.04),glass,[0,0,.11]); for(const x of [-.42,-.08]) add(g,new THREE.CylinderGeometry(.16,.16,.04,20),dark,[x,1.05,.13],[Math.PI/2,0,0]); }
  else if(name.includes('playstation')) { add(g,new THREE.BoxGeometry(.7,3.6,2.1),white,[0,0,0],[0,.05,0]); add(g,new THREE.BoxGeometry(.45,3.35,1.8),glass,[0,0,.08]); }
  else if(name.includes('gopro')||name.includes('camera')) { add(g,new THREE.BoxGeometry(1.8,1.5,.85),dark); add(g,new THREE.CylinderGeometry(.48,.48,.3,32),glass,[0,0,.52],[Math.PI/2,0,0]); add(g,new THREE.BoxGeometry(.5,.25,.04),main,[.55,.55,.44]); }
  else if(name.includes('watch')||name.includes('submariner')) { add(g,new THREE.CylinderGeometry(.78,.78,.22,48),main,[0,.2,0],[Math.PI/2,0,0]); add(g,new THREE.CylinderGeometry(.64,.64,.05,48),glass,[0,.2,.13],[Math.PI/2,0,0]); add(g,new THREE.BoxGeometry(.2,1.7,.08),dark,[0,-.9,0]); add(g,new THREE.BoxGeometry(.2,1.7,.08),dark,[0,1.3,0]); }
  else if(name.includes('eyewear')||name.includes('wayfarer')) { for(const x of [-.62,.62]) add(g,new THREE.TorusGeometry(.45,.08,12,32),dark,[x,0,0],[Math.PI/2,0,0]); add(g,new THREE.BoxGeometry(1.15,.08,.08),dark); add(g,new THREE.BoxGeometry(.08,.08,.8),dark,[-1.05,0,0]); add(g,new THREE.BoxGeometry(.08,.08,.8),dark,[1.05,0,0]); }
  else { add(g,new THREE.CylinderGeometry(.78,.92,2.7,32),main); add(g,new THREE.TorusGeometry(.72,.06,12,40),dark,[0,1.15,0]); add(g,new THREE.CylinderGeometry(.5,.5,.08,32),dark,[0,1.4,0]); }
  return g;
}
export default function Product3DTwin({ item, hero=false }) {
  const host=useRef(null);
  useEffect(()=>{ if(!host.current)return; const root=host.current; let renderer,scene,camera,controls,raf;
    try { scene=new THREE.Scene(); scene.background=new THREE.Color(0x05060c); camera=new THREE.PerspectiveCamera(32,1,.1,100); camera.position.set(0,.25,hero?8:6.5); renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,hero?1.75:1.5)); renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1.1; root.replaceChildren(renderer.domElement); renderer.domElement.style.cssText='width:100%;height:100%;display:block;touch-action:none'; scene.add(new THREE.HemisphereLight(0xeaf2ff,0x111522,1.8)); const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(4,6,5);scene.add(key);const rim=new THREE.DirectionalLight(0x866dff,1.5);rim.position.set(-4,2,-4);scene.add(rim); const floor=new THREE.Mesh(new THREE.CircleGeometry(3.4,64),new THREE.MeshBasicMaterial({color:0x111323,transparent:true,opacity:.8}));floor.rotation.x=-Math.PI/2;floor.position.y=-1.7;scene.add(floor);const object=buildProduct(item);scene.add(object);const box=new THREE.Box3().setFromObject(object);const center=box.getCenter(new THREE.Vector3());object.position.sub(center);object.position.y+=.15;controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=3.5;controls.maxDistance=11;controls.autoRotate=true;controls.autoRotateSpeed=.9;const resize=()=>{const w=Math.max(root.clientWidth,1),h=Math.max(root.clientHeight,hero?380:260);camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h,false)};resize();const ro=new ResizeObserver(resize);ro.observe(root);const animate=()=>{raf=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(raf);ro.disconnect();controls?.dispose();renderer?.dispose();scene?.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose());else o.material?.dispose?.()})}; } catch { root.innerHTML='<div style="height:100%;display:grid;place-items:center;color:#a78bff;font-size:11px;font-weight:900;letter-spacing:.16em">3D TWIN READY</div>'; return undefined; } },[item,hero]);
  return <div ref={host} aria-label={`${item?.name||'Real-world object'} 3D NFT digital twin`} style={{width:'100%',height:'100%',minHeight:hero?380:260}}/>;
}
