'use client';
import Link from 'next/link';
import dynamic from 'next/dynamic';
import { REAL_WORLD_CATALOG } from '../../lib/realWorldCatalog';
import './VaultHomeV3.css';

const Safe3DViewer = dynamic(() => import('./Safe3DViewer'), { ssr:false });

function Icon({name,size=18}){const p={arrow:<><path d="M5 13 13 5"/><path d="M7 5h6v6"/></>,search:<><circle cx="8.5" cy="8.5" r="5.5"/><path d="m13 13 3 3"/></>,shield:<><path d="M10 2.5 16 5v4.5c0 3.6-2.2 6.3-6 8-3.8-1.7-6-4.4-6-8V5Z"/><path d="m7.2 10 1.8 1.8 3.8-4"/></>,cube:<><path d="m10 2.5 6.5 3.7v7.6L10 17.5l-6.5-3.7V6.2Z"/><path d="m3.7 6.3 6.3 3.6 6.3-3.6M10 9.9v7.3"/></>};return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{p[name]}</svg>}
function Brand(){return <Link href="/" className="vv3-brand" aria-label="Voxel Vault home"><span className="vv3-brandMark"><i/><i/><i/></span><span>VOXEL <b>VAULT</b></span></Link>}
function Model({item,hero=false}){return <div style={{width:'100%',height:hero?'100%':260,minHeight:hero?420:240}}><Safe3DViewer assetUrl={item.modelUri} previewProps={{imageUrl:item.previewUri,alt:item.name}} shape={item.shape} seed={item.seed} rarity={item.rarity} material={item.material} compact={!hero} interactive showcase={hero} label={false}/></div>}
function Card({item,index}){return <Link className="vv3-objectCard" href={item.sourceUrl} target="_blank" rel="noreferrer" aria-label={`Shop ${item.name}`}><div className="vv3-objectVisual"><Model item={item}/><span className="vv3-cardIndex">{String(index+1).padStart(2,'0')}</span><span className="vv3-liveBadge"><i/> REAL OBJECT</span><span className="vv3-cardArrow" aria-hidden="true"><Icon name="arrow" size={16}/></span></div><div className="vv3-objectDetails"><div><small>{item.type}</small><h3>{item.name}</h3></div><strong>${item.priceUsd}</strong></div><div className="vv3-objectMeta"><span>{item.sourceName}</span><span>3D TWIN</span></div></Link>}
export default function RealWorldVaultHome(){const hero=REAL_WORLD_CATALOG[0];return <main className="vv3-home"><div className="vv3-noise" aria-hidden="true"/><header className="vv3-header"><div className="vv3-topbar"><Brand/><nav className="vv3-desktopNav" aria-label="Primary navigation"><Link href="/discover">Discover</Link><Link href="/marketplace">Marketplace</Link><Link href="/room">My vault</Link><Link href="/ai">Intelligence</Link></nav><div className="vv3-topActions"><Link className="vv3-roundButton" href="#collection" aria-label="Collection"><Icon name="search"/></Link><Link className="vv3-headerCta" href="/discover">Discover objects <Icon name="arrow" size={15}/></Link></div></div></header>
<section className="vv3-hero"><div className="vv3-heroGlow" aria-hidden="true"/><div className="vv3-heroCopy"><div className="vv3-eyebrow"><i/> THE PHYSICAL–DIGITAL COLLECTION</div><h1>Real objects.<br/><em>Living digital twins.</em></h1><p>Discover real-world products online, explore their 3D counterparts, and keep verified objects in your Vault.</p><div className="vv3-heroActions"><Link className="vv3-primaryCta" href="#collection">Explore objects <Icon name="arrow" size={17}/></Link><Link className="vv3-textCta" href="/discover"><span><Icon name="cube" size={14}/></span> Find more</Link></div><div className="vv3-proofRow"><span><Icon name="shield" size={16}/><b>Online source</b></span><span><Icon name="cube" size={16}/><b>Interactive 3D</b></span><span><Icon name="shield" size={16}/><b>Source labeled</b></span></div></div><div className="vv3-heroVisual"><div className="vv3-visualTop"><span><i/> REAL OBJECT</span><small>DRAG TO INSPECT</small></div><div className="vv3-modelFrame"><div className="vv3-grid"/><div className="vv3-orbit"/><Model item={hero} hero/></div><div className="vv3-featureMeta"><div><small>VERIFIED ONLINE OBJECT</small><strong>{hero.name}</strong><span>{hero.creator} · ${hero.priceUsd}</span></div><Link href={hero.sourceUrl} target="_blank" rel="noreferrer" aria-label="Shop featured object"><Icon name="arrow" size={20}/></Link></div><div className="vv3-verified"><span><Icon name="shield" size={15}/></span><div><small>SOURCE</small><b>VERIFIED</b></div></div></div></section>
<section className="vv3-signalBar"><span>REAL PRODUCTS</span><i/><span>3D DIGITAL TWINS</span><i/><span>ONLINE SOURCES</span><i/><span>OBJECT INTELLIGENCE</span></section>
<section className="vv3-collection" id="collection"><div className="vv3-collectionHead"><div><div className="vv3-sectionLabel"><span>01</span> REAL-WORLD COLLECTION</div><h2>Objects worth<br/><em>discovering.</em></h2></div><p>Every card below maps to a real-world object with an online source. The 3D reference is separately identified so Voxel Vault never pretends a generic model is manufacturer CAD.</p></div><div className="vv3-objectGrid">{REAL_WORLD_CATALOG.map((item,i)=><Card key={item.id} item={item} index={i}/>)}</div></section>
<section className="vv3-finalCta"><div><small>THE RULE</small><h2>No imaginary products.</h2><p>Real object. Real source. Real image. Real 3D reference.</p></div><Link className="vv3-primaryCta" href="/discover">Discover the collection <Icon name="arrow" size={17}/></Link></section>
<footer className="vv3-footer"><div className="vv3-footerTop"><Brand/><p>Real objects. Intelligent twins.<br/>One living collection.</p><nav><Link href="/discover">Discover</Link><Link href="/marketplace">Marketplace</Link><Link href="/room">My vault</Link><Link href="/ai">Intelligence</Link></nav></div><div className="vv3-footerBottom"><span>© 2026 VOXEL VAULT</span><div><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><span className="vv3-status"><i/> VOXEL VAULT / 2026</span></div></footer></main>}
