'use client';

import Link from 'next/link';
import { REAL_WORLD_CATALOG } from '../../lib/realWorldCatalog';
import RealWorld3DNFT from './RealWorld3DNFT';
import './VaultHomeV3.css';

function Icon({ name, size = 18 }) {
  const paths = { arrow:<><path d="M5 13 13 5"/><path d="M7 5h6v6"/></>, cube:<><path d="m10 2.5 6.5 3.7v7.6L10 17.5l-6.5-3.7V6.2Z"/><path d="m3.7 6.3 6.3 3.6 6.3-3.6M10 9.9v7.3"/></>, shield:<><path d="M10 2.5 16 5v4.5c0 3.6-2.2 6.3-6 8-3.8-1.7-6-4.4-6-8V5Z"/><path d="m7.2 10 1.8 1.8 3.8-4"/></> };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
}
function Brand(){return <Link href="/" className="vv3-brand" aria-label="Voxel Vault home"><span className="vv3-brandMark"><i/><i/><i/></span><span>VOXEL <b>VAULT</b></span></Link>}
function BuyBoth({item}){const ready=Boolean(item.fulfillmentReady&&item.purchaseAssetId);return <div style={{display:'grid',gap:9,padding:'0 14px 14px'}}>
  {ready?<Link href={`/marketplace?purchase=${encodeURIComponent(item.purchaseAssetId)}`} style={{textAlign:'center',padding:'14px 10px',borderRadius:13,background:'#fff',color:'#080a11',textDecoration:'none',fontSize:10,fontWeight:950,letterSpacing:'.07em'}}>BUY PHYSICAL + 3D NFT · ${item.customerPriceUsd}</Link>:<div style={{textAlign:'center',padding:'14px 10px',borderRadius:13,border:'1px solid rgba(167,139,250,.24)',background:'rgba(99,72,180,.07)',color:'rgba(255,255,255,.72)',fontSize:10,fontWeight:850,letterSpacing:'.06em'}}>3D NFT INCLUDED · PHYSICAL CHECKOUT COMING</div>}
  <div style={{display:'flex',justifyContent:'center',flexWrap:'wrap',gap:12,color:'rgba(255,255,255,.55)',fontSize:9}}><span>📦 physical product</span><span>🧊 3D NFT included</span><span>🏠 Vault + Room ready</span></div>
  {item.customerPriceUsd&&<div style={{textAlign:'center',color:'rgba(255,255,255,.38)',fontSize:8.5}}>Voxel Vault customer price · digital collectible included · shipping calculated at checkout</div>}
</div>}
function Card({item,index}){return <article className="vv3-objectCard">
  <div className="vv3-objectVisual"><RealWorld3DNFT item={item}/><span className="vv3-cardIndex">{String(index+1).padStart(2,'0')}</span><span className="vv3-liveBadge"><i/> REAL OBJECT</span></div>
  <div className="vv3-objectDetails"><div><small>{item.type}</small><h3>{item.name}</h3></div><strong>{item.customerPriceUsd?`$${item.customerPriceUsd}`:'Price on request'}</strong></div>
  <div className="vv3-objectMeta"><span>{item.sourceName}</span><span>3D NFT TWIN</span></div>
  <BuyBoth item={item}/>
  <div style={{padding:'0 14px 14px',fontSize:10,color:'rgba(255,255,255,.5)',lineHeight:1.5}}>Real-world product identity and source are preserved for provenance. Voxel Vault's customer price can include its configured markup; the digital collectible is presented as part of the same offer. Physical fulfillment is enabled only when the exact supplier/SKU is authorized.</div>
</article>}
export default function RealWorldCommerceHome(){const hero=REAL_WORLD_CATALOG[0];return <main className="vv3-home"><div className="vv3-noise" aria-hidden="true"/><header className="vv3-header"><div className="vv3-topbar"><Brand/><nav className="vv3-desktopNav" aria-label="Primary navigation"><Link href="/discover">Discover</Link><Link href="/marketplace">Marketplace</Link><Link href="/room">My vault</Link><Link href="/ai">Intelligence</Link></nav><Link className="vv3-headerCta" href="#collection">Shop physical + NFT <Icon name="arrow" size={15}/></Link></div></header>
<section className="vv3-hero"><div className="vv3-heroGlow" aria-hidden="true"/><div className="vv3-heroCopy"><div className="vv3-eyebrow"><i/> PHYSICAL + DIGITAL COLLECTION</div><h1>Real objects.<br/><em>3D NFTs.</em></h1><p>Choose a real-world object, see its 3D digital twin, and collect both through Voxel Vault. The physical object is fulfilled; the NFT lives in your Vault, Room, and World.</p><div className="vv3-heroActions"><Link className="vv3-primaryCta" href="#collection">Shop both <Icon name="arrow" size={17}/></Link><Link className="vv3-textCta" href="/room"><span><Icon name="cube" size={14}/></span> Open Vault</Link></div><div className="vv3-proofRow"><span><Icon name="shield" size={16}/><b>Real product</b></span><span><Icon name="cube" size={16}/><b>Automatic 3D twin</b></span><span><Icon name="shield" size={16}/><b>NFT collectible</b></span></div></div>
<div className="vv3-heroVisual"><div className="vv3-visualTop"><span><i/> 3D NFT</span><small>PHYSICAL PRODUCT + DIGITAL TWIN</small></div><RealWorld3DNFT item={hero} hero/><div className="vv3-featureMeta"><div><small>PHYSICAL + DIGITAL BUNDLE</small><strong>{hero.name}</strong><span>{hero.creator} · {hero.customerPriceUsd?`$${hero.customerPriceUsd}`:'Price on request'}</span></div></div><BuyBoth item={hero}/></div></section>
<section className="vv3-signalBar"><span>REAL PRODUCTS</span><i/><span>3D DIGITAL TWINS</span><i/><span>ONE VOXEL VAULT OFFER</span><i/><span>NFT + VAULT + WORLD</span></section>
<section className="vv3-collection" id="collection"><div className="vv3-collectionHead"><div><div className="vv3-sectionLabel"><span>01</span> SHOP THE COLLECTION</div><h2>Buy the object.<br/><em>Own the twin.</em></h2></div><p>Each listing is anchored to a real-world product source. Voxel Vault presents the physical product and 3D collectible together, with the configured customer price shown upfront and the physical supplier kept behind the fulfillment layer.</p></div><div className="vv3-objectGrid">{REAL_WORLD_CATALOG.map((item,i)=><Card key={item.id} item={item} index={i}/>)}</div></section>
<section className="vv3-finalCta"><div><small>VOXEL VAULT</small><h2>Physical in your hands. Digital in your world.</h2><p>Buy both, keep the 3D NFT in your Vault, place it in your Room, and make it discoverable in the World.</p></div><Link className="vv3-primaryCta" href="/room">Open My Room <Icon name="arrow" size={17}/></Link></section></main>}
