'use client';

import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { generateVoxelAsset } from '@/lib/nft-engine';

const DEFAULT_RARITY = { car:'Epic', villa:'Legendary', owl:'Rare', fox:'Rare', robot:'Rare', statue:'Legendary', ship:'Epic', tree:'Rare', dragon:'Mythic', mech:'Legendary', crystal:'Epic', portal:'Legendary', temple:'Epic', motorcycle:'Rare', alien:'Epic', jewelry:'Legendary', abstract:'Mythic', sword:'Epic', fortress:'Legendary', mushroom:'Rare', satellite:'Rare', totem:'Epic' };
const SURFACE = { chrome:[0.12,0.92], metallic:[0.22,0.85], gold:[0.18,0.95], weathered:[0.82,0.22], glass:[0.08,0.12], crystal:[0.08,0.32], ice:[0.1,0.2], holographic:[0.18,0.65], neon:[0.2,0.4], organic:[0.75,0.04], wood:[0.85,0.02], stone:[0.9,0.04], ceramic:[0.35,0.1], lava:[0.4,0.15], default:[0.4,0.15] };
function hashSeed(value){let hash=2166136261;const text=String(value||'showcase');for(let i=0;i<text.length;i+=1)hash=Math.imul(hash^text.charCodeAt(i),16777619);return hash>>>0;}
function makeGeometry(material){if(['glass','organic','ceramic','lava'].includes(material))return new THREE.SphereGeometry(.44,8,6);if(['crystal','ice','holographic'].includes(material))return new THREE.OctahedronGeometry(.47,0);return new THREE.BoxGeometry(.8,.8,.8);}
function signature(seed){return hashSeed(seed).toString(16).padStart(8,'0').toUpperCase();}

export default function VoxelViewer({shape='car',compact=false,label=true,interactive=true,showcase=false,rarity,seed='showcase',assetUrl='',material,onFailure}){
 const host=useRef(null),raf=useRef(0),controlsRef=useRef(null),autoRotateRef=useRef(!showcase),explodeRef=useRef(false),edgesRef=useRef(true),visibleRef=useRef(true);
 const [autoRotate,setAutoRotate]=useState(!showcase),[explode,setExplode]=useState(false),[edges,setEdges]=useState(true),[fullscreen,setFullscreen]=useState(false),[selected,setSelected]=useState(null),[assetState,setAssetState]=useState(assetUrl?'loading':'procedural');
 const effectiveRarity=rarity||DEFAULT_RARITY[shape]||'Rare';
 useEffect(()=>{
  const root=host.current;if(!root||typeof window==='undefined')return undefined;
  let renderer=null,controls=null,scene=null,gltfMixer=null,disposed=false,running=false,visibilityObserver=null,resizeObserver=null,explosion=0,lastExplosion=-1,lastTime=performance.now();let gltfScene=null;
  const resources=[],meshes=[],wires=[],clock=new THREE.Clock();
  const stop=()=>{running=false;if(raf.current)cancelAnimationFrame(raf.current);raf.current=0;};
  const start=()=>{if(running||disposed||!visibleRef.current)return;running=true;lastTime=performance.now();clock.start();raf.current=requestAnimationFrame(tick);};
  const fail=(error)=>{if(error)console.warn('Voxel Vault 3D asset fallback:',error);if(!disposed){setAssetState('fallback');onFailure?.(error);start();}};
  try{
   const probe=document.createElement('canvas');const gl=probe.getContext('webgl2',{failIfMajorPerformanceCaveat:false})||probe.getContext('webgl',{failIfMajorPerformanceCaveat:false});if(!gl){fail(new Error('WebGL unavailable'));return undefined;}gl.getExtension('WEBGL_lose_context')?.loseContext();
   scene=new THREE.Scene();scene.background=new THREE.Color('#05060c');if(!compact)scene.fog=new THREE.FogExp2('#05060c',.018);
   const camera=new THREE.PerspectiveCamera(compact?38:32,1,.1,100);renderer=new THREE.WebGLRenderer({antialias:!compact,alpha:true,powerPreference:compact?'low-power':'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,compact?1.15:1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=!compact;renderer.domElement.style.cssText='display:block;width:100%;height:100%;touch-action:none';root.replaceChildren(renderer.domElement);
   scene.add(new THREE.HemisphereLight('#e8e4ff','#070a14',compact?1.45:2.2));const key=new THREE.DirectionalLight('#fff7ea',compact?2.1:3.6);key.position.set(8,12,10);key.castShadow=!compact;scene.add(key);if(!compact){const rim=new THREE.DirectionalLight('#7657ff',1.8);rim.position.set(-8,6,-10);scene.add(rim);const cyan=new THREE.PointLight('#29d9ff',9,30,2);cyan.position.set(8,4,-8);scene.add(cyan);}
   if(showcase){const floor=new THREE.Mesh(new THREE.CircleGeometry(11,40),new THREE.MeshStandardMaterial({color:'#080b14',roughness:.78,metalness:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.45;scene.add(floor);resources.push(floor.geometry,floor.material);const ring=new THREE.Mesh(new THREE.RingGeometry(4.7,4.82,48),new THREE.MeshBasicMaterial({color:'#8667ff',transparent:true,opacity:.34,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-2.08;scene.add(ring);resources.push(ring.geometry,ring.material);}
   const group=new THREE.Group();scene.add(group);const asset=generateVoxelAsset({shape,seed,rarity:effectiveRarity,material});const matKey=asset.material||material||'default',surface=SURFACE[matKey]||SURFACE.default,colors=asset.palette||['#9b7cff'],voxels=asset.voxels||[],geometry=makeGeometry(matKey);resources.push(geometry);
   const buckets=new Map();for(const voxel of voxels){const index=voxel[3]??0;if(!buckets.has(index))buckets.set(index,[]);buckets.get(index).push(voxel);}const bounds=new THREE.Box3();
   for(const [colorIndex,bucket] of buckets){const [roughness,metalness]=surface;const transparent=['glass','crystal','ice'].includes(matKey);const opacity=matKey==='glass'?.72:matKey==='crystal'?.86:matKey==='ice'?.82:1;const mat=new THREE.MeshStandardMaterial({color:colors[colorIndex]||colors[0],roughness,metalness,transparent,opacity});if(['holographic','neon','lava'].includes(matKey)){mat.emissive=new THREE.Color(colors[colorIndex]||colors[0]);mat.emissiveIntensity=matKey==='neon'?.32:.22;}const mesh=new THREE.InstancedMesh(geometry,mat,bucket.length);mesh.frustumCulled=true;mesh.castShadow=!compact;mesh.receiveShadow=!compact;mesh.userData.voxels=bucket;mesh.userData.base=[];for(const voxel of bucket){const position=new THREE.Vector3(voxel[0]*.8,voxel[1]*.8-2,voxel[2]*.8);mesh.userData.base.push(position);bounds.expandByPoint(position);}const matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion(),scale=new THREE.Vector3(1,1,1);for(let i=0;i<bucket.length;i+=1){matrix.compose(mesh.userData.base[i],quaternion,scale);mesh.setMatrixAt(i,matrix);}mesh.instanceMatrix.needsUpdate=true;group.add(mesh);meshes.push(mesh);resources.push(mat);if(!compact&&geometry.type==='BoxGeometry'){const wireMaterial=new THREE.MeshBasicMaterial({color:'#c9bdff',transparent:true,opacity:.09,wireframe:true});const wire=new THREE.InstancedMesh(geometry,wireMaterial,bucket.length);wire.frustumCulled=true;wire.userData.base=mesh.userData.base;for(let i=0;i<bucket.length;i+=1){matrix.compose(mesh.userData.base[i],quaternion,scale);wire.setMatrixAt(i,matrix);}wire.instanceMatrix.needsUpdate=true;group.add(wire);wires.push(wire);resources.push(wireMaterial);}}
   const center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),dimension=Math.max(size.x,size.y,size.z,2.5);
   const frameObject=(object)=>{const b=new THREE.Box3().setFromObject(object),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),d=Math.max(s.x,s.y,s.z,2);const distance=d/Math.tan(THREE.MathUtils.degToRad(camera.fov/2))*0.62;camera.position.copy(c).add(new THREE.Vector3(distance*.8,distance*.45,distance));camera.near=Math.max(.01,distance/100);camera.far=Math.max(100,distance*20);camera.updateProjectionMatrix();if(controls){controls.target.copy(c);controls.minDistance=Math.max(1.5,distance*.45);controls.maxDistance=Math.max(10,distance*5);controls.update();}else camera.lookAt(c);};
   camera.position.copy(center).add(new THREE.Vector3(dimension*1.08,dimension*.72,dimension*1.15));
   if(interactive){controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.enablePan=false;controls.autoRotate=autoRotateRef.current;controls.autoRotateSpeed=.45;controls.minDistance=Math.max(3.2,dimension*.85);controls.maxDistance=Math.max(12,dimension*4.5);controls.target.copy(center);controlsRef.current=controls;controls.update();}
   if(assetUrl){const loader=new GLTFLoader();loader.setCrossOrigin?.('anonymous');loader.load(assetUrl,(gltf)=>{if(disposed)return;gltfScene=gltf.scene;gltfScene.traverse(o=>{if(o.isMesh){o.castShadow=!compact;o.receiveShadow=!compact;if(o.material){if(Array.isArray(o.material))o.material.forEach(m=>{if(m) m.needsUpdate=true;});else o.material.needsUpdate=true;}}});group.visible=false;scene.add(gltfScene);frameObject(gltfScene);if(gltf.animations?.length){gltfMixer=new THREE.AnimationMixer(gltfScene);gltf.animations.forEach(clip=>gltfMixer.clipAction(clip).play());}setAssetState('loaded');},undefined,(error)=>{setAssetState('fallback');fail(error);});}
   const resize=()=>{if(disposed)return;const w=Math.max(root.clientWidth,1),h=Math.max(root.clientHeight,compact?180:320);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();if(gltfScene)frameObject(gltfScene);};resize();resizeObserver=new ResizeObserver(resize);resizeObserver.observe(root);visibilityObserver=new IntersectionObserver(([entry])=>{visibleRef.current=Boolean(entry?.isIntersecting);if(visibleRef.current)start();else stop();},{rootMargin:'180px'});visibilityObserver.observe(root);
   const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();const click=(event)=>{if(!interactive||!group.visible)return;const rect=renderer.domElement.getBoundingClientRect();pointer.x=((event.clientX-rect.left)/rect.width)*2-1;pointer.y=-((event.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes,false)[0];if(hit&&hit.instanceId!==undefined){const data=hit.object.userData.voxels[hit.instanceId];setSelected({x:data[0],y:data[1],z:data[2],color:colors[data[3]]});}};renderer.domElement.addEventListener('click',click);
   const matrix=new THREE.Matrix4(),quaternion=new THREE.Quaternion(),scale=new THREE.Vector3(1,1,1),centerLocal=bounds.getCenter(new THREE.Vector3());
   function tick(now){if(disposed)return;const delta=Math.min((now-lastTime)/1000,.05);lastTime=now;const targetExplosion=explodeRef.current?1:0;explosion=THREE.MathUtils.lerp(explosion,targetExplosion,.08);const idleTime=clock.getElapsedTime();if(controls){controls.autoRotate=autoRotateRef.current;controls.update();}else if(autoRotateRef.current)group.rotation.y+=delta*.22;if(showcase){group.position.y=Math.sin(idleTime*1.45)*.075;group.rotation.x=Math.sin(idleTime*.7)*.025;}wires.forEach(wire=>{wire.visible=edgesRef.current;});if(Math.abs(explosion-lastExplosion)>.002){for(const mesh of meshes){for(let i=0;i<mesh.userData.base.length;i+=1){const base=mesh.userData.base[i];const direction=base.clone().sub(centerLocal);if(direction.lengthSq()<.001)direction.set(0,1,0);direction.normalize();matrix.compose(base.clone().addScaledVector(direction,explosion*1.15),quaternion,scale);mesh.setMatrixAt(i,matrix);}mesh.instanceMatrix.needsUpdate=true;}lastExplosion=explosion;}if(gltfMixer)gltfMixer.update(delta);renderer.render(scene,camera);if(running)raf.current=requestAnimationFrame(tick);}
   start();return()=>{disposed=true;stop();resizeObserver?.disconnect();visibilityObserver?.disconnect();renderer?.domElement?.removeEventListener('click',click);controls?.dispose();gltfMixer?.stopAllAction();scene?.traverse(o=>{if(o.geometry&&!resources.includes(o.geometry))o.geometry.dispose?.();if(o.material&&!resources.includes(o.material))o.material.dispose?.();});resources.forEach(resource=>resource.dispose?.());renderer?.dispose();renderer?.forceContextLoss?.();if(root.contains(renderer?.domElement))root.removeChild(renderer.domElement);controlsRef.current=null;};
  }catch(error){fail(error);return undefined;}
 },[shape,compact,interactive,showcase,effectiveRarity,seed,assetUrl,material,onFailure]);
 const toggleRotate=()=>{const next=!autoRotate;autoRotateRef.current=next;setAutoRotate(next);};const toggleExplode=()=>{const next=!explode;explodeRef.current=next;setExplode(next);};const toggleEdges=()=>{const next=!edges;edgesRef.current=next;setEdges(next);};const reset=()=>{explodeRef.current=false;setExplode(false);controlsRef.current?.reset();};const full=async()=>{try{if(!document.fullscreenElement)await host.current?.requestFullscreen();else await document.exitFullscreen();}catch{}};
 useEffect(()=>{const handler=()=>setFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler);},[]);
 return <div ref={host} className={`voxelViewer ${compact?'compact':''}`} style={{position:'relative',width:'100%',height:'100%',minHeight:compact?180:320,overflow:'hidden',display:'grid',placeItems:'center',background:'radial-gradient(circle at 50% 40%,rgba(112,79,255,.12),transparent 48%),#05060c',borderRadius:18}}>
  {label&&<><div className="vvBadge">3D ASSET · {effectiveRarity.toUpperCase()}</div><div className="vvDna">DNA · {signature(seed)}</div></>}{showcase&&<div className="vvShowcase">✦ SHOWCASE · DRAG TO INSPECT</div>}{assetUrl&&<div className={`vvLoadState ${assetState}`}>{assetState==='loading'?'Loading source…':assetState==='loaded'?'LIVE ASSET':'Procedural fallback'}</div>}{interactive&&<div className="vvTools"><button type="button" onClick={toggleRotate}>{autoRotate?'Pause':'Rotate'}</button><button type="button" onClick={toggleExplode}>{explode?'Assemble':'Explode'}</button><button type="button" onClick={toggleEdges}>{edges?'Edges':'Clean'}</button><button type="button" onClick={reset}>Reset</button><button type="button" onClick={full}>{fullscreen?'Exit':'Full'}</button></div>}{selected&&<div className="vvSelected">X {selected.x} · Y {selected.y} · Z {selected.z}</div>}
  <style jsx>{`.vvBadge,.vvDna,.vvShowcase,.vvSelected,.vvLoadState{position:absolute;z-index:4;border:1px solid rgba(255,255,255,.1);background:rgba(5,6,12,.72);backdrop-filter:blur(10px);border-radius:999px;padding:6px 9px;font-size:8px;letter-spacing:.12em;color:#c7c0ff}.vvBadge{left:10px;top:10px}.vvDna{right:10px;bottom:10px;color:#aaa1d8}.vvShowcase{left:50%;top:10px;transform:translateX(-50%);white-space:nowrap;color:#e6e0ff}.vvSelected{left:10px;bottom:10px}.vvLoadState{left:10px;bottom:10px;color:#8f96a8}.vvLoadState.loaded{color:#9fe6c0;border-color:rgba(80,220,150,.18)}.vvLoadState.fallback{color:#d6c9ff}.vvTools{position:absolute;right:10px;top:10px;z-index:5;display:flex;gap:5px;flex-wrap:wrap;justify-content:flex-end;max-width:300px}.vvTools button{border:1px solid rgba(255,255,255,.12);background:rgba(6,7,14,.78);color:#fff;border-radius:9px;padding:7px 9px;font-size:10px;cursor:pointer}.vvTools button:hover{border-color:#8b70ff}.compact .vvBadge,.compact .vvDna,.compact .vvLoadState{display:none}`}</style>
 </div>;
}
