'use client';

import { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { generateVoxelAsset } from '@/lib/nft-engine';

const DEFAULT_RARITY={car:'Epic',villa:'Legendary',owl:'Rare',fox:'Rare',robot:'Rare',statue:'Legendary',ship:'Epic',tree:'Rare'};

export default function VoxelViewer({shape='car',compact=false,label=true,interactive=true,showcase=false,rarity,seed='showcase'}){
  const host=useRef(null),frame=useRef(0),autoRotateRef=useRef(!showcase),gridRef=useRef(false),explodeTargetRef=useRef(false),edgesRef=useRef(true);
  const [selected,setSelected]=useState(null),[hovered,setHovered]=useState(null),[explode,setExplode]=useState(false),[edges,setEdges]=useState(true),[autoRotate,setAutoRotate]=useState(!showcase),[grid,setGrid]=useState(false);
  const effectiveRarity=rarity||DEFAULT_RARITY[shape]||'Rare';
  useEffect(()=>{
    if(!host.current)return;const root=host.current;const scene=new THREE.Scene();scene.background=new THREE.Color('#070811');
    const camera=new THREE.PerspectiveCamera(32,1,.1,1000);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;root.appendChild(renderer.domElement);
    const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.065;controls.minDistance=8;controls.maxDistance=52;controls.enablePan=false;controls.autoRotate=autoRotateRef.current;controls.autoRotateSpeed=.6;
    scene.add(new THREE.HemisphereLight('#ddd8ff','#0b101a',2.2));const key=new THREE.DirectionalLight('#fff8ed',4);key.position.set(11,20,14);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const rim=new THREE.PointLight('#7755ff',42,60);rim.position.set(-12,8,-10);scene.add(rim);const fill=new THREE.PointLight('#32d8ff',20,45);fill.position.set(10,5,-8);scene.add(fill);
    const floor=new THREE.Mesh(new THREE.CircleGeometry(14,64),new THREE.MeshStandardMaterial({color:'#0a0d15',roughness:.78,metalness:.12}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.4;floor.receiveShadow=true;scene.add(floor);
    const ring=new THREE.Mesh(new THREE.RingGeometry(5.8,5.86,96),new THREE.MeshBasicMaterial({color:'#7657ff',transparent:true,opacity:.34,side:THREE.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=-2.38;scene.add(ring);
    const gridHelper=new THREE.GridHelper(24,24,'#25203d','#151725');gridHelper.position.y=-2.39;scene.add(gridHelper);
    const group=new THREE.Group();scene.add(group);const asset=generateVoxelAsset({shape,seed,rarity:effectiveRarity});const colors=asset.palette;const voxels=asset.voxels;const geometry=new THREE.BoxGeometry(.72,.72,.72);const edgeGeometry=new THREE.EdgesGeometry(geometry);const buckets=new Map();voxels.forEach(v=>{if(!buckets.has(v[3]))buckets.set(v[3],[]);buckets.get(v[3]).push(v)});
    const meshes=[],edgeMeshes=[],materials=[];
    buckets.forEach((arr,c)=>{const material=new THREE.MeshStandardMaterial({color:colors[c],roughness:c===3?.32:.46,metalness:c===3?.2:.06,emissive:colors[c],emissiveIntensity:0});materials.push(material);const mesh=new THREE.InstancedMesh(geometry,material,arr.length);mesh.castShadow=true;mesh.receiveShadow=true;mesh.frustumCulled=false;mesh.userData.voxels=arr;mesh.userData.basePositions=arr.map(v=>new THREE.Vector3(v[0]*.76,v[1]*.76-2.1,v[2]*.76));const m=new THREE.Matrix4(),q=new THREE.Quaternion(),s=new THREE.Vector3(1,1,1);arr.forEach((v,i)=>{m.compose(mesh.userData.basePositions[i],q,s);mesh.setMatrixAt(i,m)});mesh.instanceMatrix.needsUpdate=true;group.add(mesh);meshes.push(mesh);
      const edgeMaterial=new THREE.LineBasicMaterial({color:'#b8a8ff',transparent:true,opacity:.18});const line=new THREE.LineSegments(edgeGeometry,edgeMaterial);line.userData.basePositions=mesh.userData.basePositions;line.userData.count=arr.length;line.userData.mesh=mesh;group.add(line);edgeMeshes.push(line);
    });
    const box3=new THREE.Box3();voxels.forEach(v=>box3.expandByPoint(new THREE.Vector3(v[0]*.76,v[1]*.76-2.1,v[2]*.76)));const size=box3.getSize(new THREE.Vector3()),center=box3.getCenter(new THREE.Vector3());const maxDim=Math.max(size.x,size.y,size.z);controls.target.copy(center);camera.position.copy(center).add(new THREE.Vector3(maxDim*1.55,maxDim*1.05,maxDim*1.75));
    const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();
    const pointerAt=e=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1};
    const resetMaterial=()=>materials.forEach(m=>{m.emissiveIntensity=0});
    const pick=e=>{if(!interactive)return;pointerAt(e);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes,false)[0];resetMaterial();if(!hit||hit.instanceId===undefined){setHovered(null);renderer.domElement.style.cursor='grab';return}const data=hit.object.userData.voxels[hit.instanceId];const item={x:data[0],y:data[1],z:data[2],color:colors[data[3]],instance:hit.instanceId};setHovered(item);hit.object.material.emissiveIntensity=.32;renderer.domElement.style.cursor='pointer'};
    const click=e=>{if(!interactive)return;pointerAt(e);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(meshes,false)[0];if(!hit||hit.instanceId===undefined){setSelected(null);return}const data=hit.object.userData.voxels[hit.instanceId];setSelected({x:data[0],y:data[1],z:data[2],color:colors[data[3]],instance:hit.instanceId})};
    renderer.domElement.addEventListener('pointermove',pick);renderer.domElement.addEventListener('pointerleave',()=>{resetMaterial();setHovered(null)});renderer.domElement.addEventListener('click',click);
    const resize=()=>{const r=root.getBoundingClientRect();const w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(root);
    let explosionAmount=0;const animate=()=>{controls.autoRotate=autoRotateRef.current;gridHelper.visible=gridRef.current;edgeMeshes.forEach(x=>x.visible=edgesRef.current);const target=explodeTargetRef.current?1:0;explosionAmount=THREE.MathUtils.lerp(explosionAmount,target,.075);group.children.forEach(obj=>{if(!obj.userData.basePositions)return;const m=new THREE.Matrix4(),q=new THREE.Quaternion(),s=new THREE.Vector3(1,1,1);obj.userData.basePositions.forEach((p,i)=>{const dir=p.clone().sub(center);if(dir.lengthSq()<.001)dir.set(0,1,0);dir.normalize();const pos=p.clone().addScaledVector(dir,1.8*explosionAmount);if(obj.isInstancedMesh){m.compose(pos,q,s);obj.setMatrixAt(i,m)}else{obj.position.copy(pos)}});if(obj.isInstancedMesh)obj.instanceMatrix.needsUpdate=true});controls.update();renderer.render(scene,camera);frame.current=requestAnimationFrame(animate)};animate();
    return()=>{ro.disconnect();cancelAnimationFrame(frame.current);controls.dispose();renderer.domElement.removeEventListener('pointermove',pick);renderer.domElement.removeEventListener('click',click);renderer.dispose();geometry.dispose();edgeGeometry.dispose();materials.forEach(m=>m.dispose());edgeMeshes.forEach(m=>m.material.dispose());floor.geometry.dispose();floor.material.dispose();ring.geometry.dispose();ring.material.dispose();gridHelper.geometry.dispose();gridHelper.material.dispose();root.removeChild(renderer.domElement)};
  },[shape,interactive,effectiveRarity,seed]);
  const setRotation=()=>{const next=!autoRotate;autoRotateRef.current=next;setAutoRotate(next)};const setGridMode=()=>{const next=!grid;gridRef.current=next;setGrid(next)};const setExploded=()=>{const next=!explode;explodeTargetRef.current=next;setExplode(next)};const setEdgesMode=()=>{const next=!edges;edgesRef.current=next;setEdges(next)};
  return <div className={`voxelViewer ${compact?'compact':''}`} ref={host}>
    {label&&<><div className="viewerBadge">REAL 3D VOXEL · {effectiveRarity.toUpperCase()} · {seed.toUpperCase()}</div><div className="dnaBadge">DNA · DETERMINISTIC</div></>}
    {interactive&&<div className="viewerTools"><button type="button" onClick={setRotation}>{autoRotate?'⏸ Pause':'▶ Rotate'}</button><button type="button" onClick={setExploded}>{explode?'🧩 Assemble':'💥 Explode'}</button><button type="button" onClick={setGridMode}>▦ Grid</button><button type="button" onClick={setEdgesMode}>{edges?'◇ Edges':'◇ Clean'}</button></div>}
    {selected&&<div className="voxelInfo"><b>VOXEL SELECTED</b><span>X {selected.x} · Y {selected.y} · Z {selected.z}</span><span><i style={{background:selected.color}}/> {selected.color}</span></div>}
    {hovered&&!selected&&<div className="voxelHover">VOXEL {hovered.x},{hovered.y},{hovered.z}</div>}
    <style jsx>{`.viewerTools{position:absolute;top:12px;right:12px;z-index:5;display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.viewerTools button{border:1px solid rgba(255,255,255,.12);background:rgba(8,8,17,.82);color:#fff;border-radius:9px;padding:7px 9px;font-size:11px;font-weight:700;cursor:pointer;backdrop-filter:blur(8px)}.viewerTools button:hover{border-color:#8066ff;background:rgba(118,89,255,.55)}.voxelInfo,.voxelHover,.dnaBadge{position:absolute;z-index:5;padding:9px 11px;border-radius:11px;background:rgba(8,8,17,.86);border:1px solid rgba(118,89,255,.4);color:#dfe2ff;font-size:11px;font-family:monospace;backdrop-filter:blur(10px);display:flex;gap:8px;flex-wrap:wrap}.voxelInfo{bottom:12px;left:12px}.voxelInfo b{width:100%;color:#fff}.voxelInfo i{display:inline-block;width:9px;height:9px;border-radius:3px;vertical-align:-1px}.voxelHover{bottom:12px;left:12px;border-color:rgba(118,89,255,.2);pointer-events:none}.dnaBadge{right:12px;bottom:12px;font-size:8px;letter-spacing:1px;color:#a99bff}.compact .viewerTools{transform:scale(.86);transform-origin:top right}.compact .voxelInfo,.compact .voxelHover{font-size:9px;padding:6px 8px}@media(max-width:600px){.viewerTools{max-width:190px}.viewerTools button{font-size:10px;padding:7px}.voxelInfo{max-width:calc(100% - 24px)}}`}</style>
  </div>;
}
