'use client';
import { useMemo, useState } from 'react';
import Link from 'next/link';

const GATES = ['H','X','Y','Z','S','T'];
export default function QuantumPage(){
 const [qubits,setQubits]=useState(2); const [ops,setOps]=useState<Array<{gate:string;qubit:number}>>([]); const [result,setResult]=useState<any[]>([]); const [busy,setBusy]=useState(false);
 const circuit=useMemo(()=>ops.map((x,i)=>`${x.gate}q${x.qubit}`).join(' · ')||'Tap a gate to build your circuit',[ops]);
 function add(gate:string){setOps(v=>[...v,{gate,qubit:v.length%qubits}]);setResult([])}
 async function run(){setBusy(true);try{const r=await fetch('/api/quantum/simulate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({qubits,operations:ops.length?ops:[{gate:'H',qubit:0}]})});const d=await r.json();setResult(d.results||[])}finally{setBusy(false)}}
 return <main className="page"><header><Link href="/">‹</Link><div><small>VOXEL LABS</small><h1>Quantum Lab</h1></div><Link href="/room">◇</Link></header>
 <section className="hero"><span>⚛︎</span><small>QUANTUM COMPUTING</small><h2>Explore the strange.</h2><p>Build small circuits and inspect probability states. This is a classical simulation, not a claim of direct quantum-hardware access.</p></section>
 <section className="panel"><div className="row"><b>Qubits</b><strong>{qubits}</strong></div><input aria-label="Number of qubits" type="range" min="1" max="8" value={qubits} onChange={e=>{setQubits(Number(e.target.value));setOps([]);setResult([])}}/><div className="wires">{Array.from({length:qubits},(_,i)=><div key={i}><span>q{i}</span><i/></div>)}</div></section>
 <section className="panel"><small>GATE PALETTE</small><div className="gates">{GATES.map(g=><button key={g} onClick={()=>add(g)}>{g}</button>)}</div><div className="circuit" aria-live="polite">{circuit}</div><div className="controls"><button className="run" onClick={run} disabled={busy}>{busy?'Running…':'Run simulation'}</button><button className="clear" onClick={()=>{setOps([]);setResult([])}}>Clear</button></div></section>
 {result.length>0&&<section className="states"><small>MEASUREMENT PROBABILITIES</small>{result.map(x=><div key={x.state}><b>|{x.state}⟩</b><span>{(x.probability*100).toFixed(2)}%</span><i style={{width:`${Math.max(2,x.probability*100)}%`}}/></div>)}</section>}
 <section className="cards"><article><b>🧠 AI + Science</b><p>Ask Voxel AI to explain your circuit, compare algorithms, or turn a result into a plain-English lesson.</p></article><article><b>🌐 Live knowledge</b><p>Approved public HTTPS sources can enrich research workflows while credentials stay server-side.</p></article><article><b>🧊 Quantum collectibles</b><p>Save experiments as scientific objects in your Vault, with circuit settings and results as provenance metadata.</p></article></section>
 <footer><Link href="/">Find</Link><Link href="/room">Vault</Link><Link href="/receipt">Scan</Link><Link href="/terms">Terms</Link></footer>
 <style jsx>{`.page{min-height:100vh;background:#05060b;color:#f6f7fb;padding:0 16px 40px;font-family:Inter,system-ui,sans-serif}.page header{height:70px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #ffffff14}.page header a{color:#fff;text-decoration:none;font-size:22px}.page header div{text-align:center}.page header small{font-size:7px;letter-spacing:.18em;color:#a996ff}.page h1{font-size:18px;margin:4px 0}.hero{padding:30px 0 18px}.hero>span{font-size:48px;color:#a996ff}.hero>small{display:block;margin-top:10px;color:#8e7df2;font-size:8px;letter-spacing:.16em;font-weight:900}.hero h2{font-size:34px;letter-spacing:-.05em;margin:8px 0}.hero p,.cards article p{font-size:11px;line-height:1.55;color:#7e8798}.panel,.states,.cards article{border:1px solid #ffffff12;background:#ffffff06;border-radius:18px;padding:15px;margin-top:10px}.row{display:flex;justify-content:space-between;font-size:11px}.panel input{width:100%;margin:14px 0}.wires{display:grid;gap:8px}.wires>div{display:flex;gap:8px;align-items:center}.wires span{width:20px;color:#778193;font-size:8px}.wires i{height:1px;flex:1;background:#ffffff20}.gates{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.gates button,.clear{width:42px;height:42px;border:1px solid #ffffff16;border-radius:11px;background:#0b0d15;color:#fff;font-weight:900}.circuit{min-height:48px;margin-top:12px;border:1px dashed #a995ff44;border-radius:11px;display:grid;place-items:center;color:#788295;font-size:9px;padding:8px;text-align:center}.controls{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:9px}.run{padding:13px;border:0;border-radius:12px;background:#f5f6f9;color:#08090d;font-weight:900;font-size:10px}.clear{width:auto;height:auto;padding:0 14px;color:#b6bdca}.states>small,.panel>small{font-size:7px;letter-spacing:.15em;color:#9e8dff;font-weight:900}.states>div{position:relative;display:grid;grid-template-columns:60px 1fr 45px;gap:8px;align-items:center;min-height:42px;border-bottom:1px solid #ffffff0b}.states>div:last-child{border:0}.states b{font-family:ui-monospace;font-size:11px}.states span{font-size:10px;color:#aab1bf;text-align:right}.states i{grid-column:2/4;height:4px;border-radius:99px;background:linear-gradient(90deg,#a995ff,#61dcff);display:block}.cards{margin-top:20px}.cards article b{font-size:12px}.cards article p{margin:6px 0 0}.cards article{margin-top:10px}footer{display:flex;justify-content:center;gap:18px;margin-top:20px}footer a{color:#687184;text-decoration:none;font-size:9px}`}</style></main>;
}