'use client';

import Link from 'next/link';

const items = [
  { icon: '👟', name: 'Your first collectible', meta: 'Verified purchase · Ready for 3D' },
  { icon: '☕', name: 'Coffee memory', meta: 'Purchase collectible · Aug 2026' },
  { icon: '🧸', name: 'Physical object', meta: 'NFT + QR · Provenance attached' },
];

export default function RoomPage() {
  return <main className="page"><header><Link href="/" className="back">‹</Link><div><small>YOUR VAULT</small><h1>My Room</h1></div><Link href="/receipt" className="scan">▣ Scan</Link></header>
    <section className="room"><div className="floor"/><div className="wall"/><div className="roomLabel"><small>3D COLLECTION</small><b>Your things, in one place.</b><span>Every verified collectible can have a home here.</span></div><div className="objects">{items.map((item,i)=><div className={`object o${i}`} key={item.name}><span>{item.icon}</span><b>{item.name}</b></div>)}</div></section>
    <section className="list"><div className="head"><span>COLLECTED</span><b>{items.length}</b></div>{items.map(item=><article key={item.name}><strong>{item.icon}</strong><div><b>{item.name}</b><small>{item.meta}</small></div><span>›</span></article>)}</section>
    <Link className="discover" href="/">Find more objects →</Link><footer><Link href="/terms">Terms</Link><Link href="/privacy">Privacy</Link></footer>
    <style jsx>{`.page{min-height:100vh;background:#05060b;color:#f6f7fb;padding:0 16px 35px;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.page header{height:70px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08)}.back,.scan{color:#fff;text-decoration:none}.back{font-size:30px}.scan{font-size:10px;padding:8px 10px;border:1px solid rgba(255,255,255,.1);border-radius:999px}.page header div{text-align:center}.page header small{font-size:7px;letter-spacing:.18em;color:#9e8dff}.page h1{font-size:18px;margin:3px 0}.room{height:430px;position:relative;margin-top:16px;border:1px solid rgba(255,255,255,.08);border-radius:24px;overflow:hidden;background:linear-gradient(155deg,#121526 0%,#080a11 65%)}.wall{position:absolute;inset:0;background:linear-gradient(135deg,transparent 50%,rgba(137,110,255,.1));clip-path:polygon(0 0,100% 0,73% 65%,0 65%)}.floor{position:absolute;left:-15%;right:-15%;bottom:-10%;height:55%;background:repeating-linear-gradient(90deg,rgba(255,255,255,.025) 0 1px,transparent 1px 48px),linear-gradient(170deg,#0b0d16,#171927);transform:perspective(500px) rotateX(58deg);transform-origin:bottom}.roomLabel{position:absolute;top:20px;left:20px;display:grid;gap:4px}.roomLabel small{font-size:7px;color:#9e8dff;letter-spacing:.14em;font-weight:900}.roomLabel b{font-size:17px}.roomLabel span{font-size:9px;color:#737d90}.objects{position:absolute;inset:0}.object{position:absolute;width:92px;height:92px;border-radius:22px;display:grid;place-items:center;background:rgba(255,255,255,.05);border:1px solid rgba(255,255,255,.1);backdrop-filter:blur(12px);box-shadow:0 20px 40px rgba(0,0,0,.35)}.object span{font-size:42px;filter:drop-shadow(0 12px 16px rgba(0,0,0,.4))}.object b{position:absolute;bottom:-23px;white-space:nowrap;font-size:8px;color:#adb5c5}.o0{left:12%;top:49%}.o1{left:48%;top:38%}.o2{right:9%;top:55%}.list{margin-top:18px;border:1px solid rgba(255,255,255,.08);border-radius:20px;overflow:hidden;background:rgba(255,255,255,.03)}.head{display:flex;justify-content:space-between;padding:13px 15px;color:#858fa1;font-size:8px;letter-spacing:.12em;border-bottom:1px solid rgba(255,255,255,.07)}.head b{color:#fff}.list article{display:flex;align-items:center;gap:12px;padding:13px 15px;border-bottom:1px solid rgba(255,255,255,.06)}.list article:last-child{border-bottom:0}.list strong{font-size:27px}.list article div{flex:1}.list article b,.list article small{display:block}.list article b{font-size:11px}.list article small{font-size:8px;color:#707a8c;margin-top:3px}.list article>span{color:#7e8798}.discover{display:block;text-align:center;margin-top:13px;color:#a796ff;text-decoration:none;font-size:10px;font-weight:900}footer{display:flex;justify-content:center;gap:18px;margin-top:22px}footer a{font-size:9px;color:#626b7d;text-decoration:none}@media(min-width:700px){.page{max-width:620px;margin:auto}}`}</style>
  </main>;
}
