'use client';

import { useEffect, useState } from 'react';
import { supabaseBrowser } from '@/lib/supabase-browser';

export default function Home() {
  const [email, setEmail] = useState(''); const [user, setUser] = useState(null); const [assets, setAssets] = useState([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => {
    supabaseBrowser.auth.getUser().then(({ data }) => setUser(data.user ?? null));
    const { data: listener } = supabaseBrowser.auth.onAuthStateChange((_event, session) => setUser(session?.user ?? null));
    supabaseBrowser.from('assets').select('id,title,description,price_cents,currency').eq('status', 'published').order('created_at', { ascending: false }).then(({ data, error }) => { if (!error) setAssets(data ?? []); });
    return () => listener.subscription.unsubscribe();
  }, []);
  async function signIn() { setLoading(true); setMessage(''); const { error } = await supabaseBrowser.auth.signInWithOtp({ email, options: { emailRedirectTo: window.location.origin } }); setLoading(false); setMessage(error ? error.message : 'Check your email for the VoxelVault sign-in link.'); }
  async function buy(assetId) { if (!user) { setMessage('Sign in first, then choose Buy.'); return; } setLoading(true); setMessage('Opening secure Stripe Checkout…'); const { data: { session } } = await supabaseBrowser.auth.getSession(); const response = await fetch('/api/checkout', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session?.access_token ?? ''}` }, body: JSON.stringify({ assetId }) }); const result = await response.json(); setLoading(false); if (!response.ok) { setMessage(result.error || 'Checkout failed.'); return; } window.location.href = result.url; }
  return <main style={{minHeight:'100vh',background:'#090b12',color:'#f7f8fb',fontFamily:'system-ui,sans-serif'}}><nav style={{display:'flex',justifyContent:'space-between',padding:'22px 6vw',borderBottom:'1px solid #202432'}}><strong style={{fontSize:24}}>VoxelVault</strong><span style={{color:'#9ba3b4'}}>{user ? user.email : 'Creator 3D marketplace'}</span></nav><section style={{maxWidth:1100,margin:'0 auto',padding:'72px 24px 32px'}}><p style={{color:'#8b5cf6',fontWeight:700}}>3D ASSET MARKETPLACE</p><h1 style={{fontSize:'clamp(42px,7vw,82px)',lineHeight:.98,margin:'12px 0 22px'}}>Buy worlds.<br/>Build worlds.</h1><p style={{maxWidth:650,color:'#aab1c0',fontSize:19}}>Discover downloadable 3D assets for games, VR, animation and creative projects. Secure checkout and private digital delivery are built in.</p><div style={{marginTop:28,padding:18,background:'#111522',border:'1px solid #252a39',borderRadius:16,maxWidth:620}}>{!user && <div style={{display:'flex',gap:10}}><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" type="email" style={{flex:1,padding:13,borderRadius:10,border:'1px solid #34394a',background:'#0b0e17',color:'white'}}/><button disabled={loading||!email} onClick={signIn} style={{padding:'13px 18px',borderRadius:10,border:0,cursor:'pointer'}}>Sign in</button></div>}{message && <p style={{color:'#aab1c0'}}>{message}</p>}</div></section><section style={{maxWidth:1100,margin:'0 auto',padding:'24px'}}><h2>Featured assets</h2>{assets.length===0?<div style={{padding:30,border:'1px dashed #34394a',borderRadius:16,color:'#9ba3b4'}}>No published assets yet. Your marketplace database is ready for its first creator listing.</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(240px,1fr))',gap:18}}>{assets.map(asset=><article key={asset.id} style={{background:'#111522',border:'1px solid #252a39',borderRadius:16,padding:20}}><div style={{height:150,borderRadius:12,background:'linear-gradient(135deg,#181c2b,#0d1018)',display:'grid',placeItems:'center',fontSize:48}}>◆</div><h3>{asset.title}</h3><p style={{color:'#9ba3b4'}}>{asset.description}</p><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong>${(asset.price_cents/100).toFixed(2)}</strong><button disabled={loading} onClick={()=>buy(asset.id)} style={{padding:'10px 14px',borderRadius:9,border:0,cursor:'pointer'}}>Buy</button></div></article>)}</div>}</section></main>;
}
