const MODEL_BASE='https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Assets/main/2.0';

// Real-world shopping objects. Product source and 3D reference are deliberately
// separate: a generic licensed reference model is never represented as exact
// manufacturer CAD. Exact product twins can be upgraded later when licensed assets
// are available.
const items=[
{id:'apple-airpods-pro-3',name:'Apple AirPods Pro 3',creator:'Apple',type:'Audio',family:'artifact',shape:'jewelry',material:'ceramic',rarity:'Rare',priceUsd:'249',sourceName:'Apple',sourceUrl:'https://www.apple.com/shop/buy-airpods/airpods-pro-3',previewUri:'https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/Sunglasses/glTF-Binary/Sunglasses.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'stanley-quencher-40oz',name:'Stanley Quencher H2.0 FlowState 40 oz',creator:'Stanley 1913',type:'Drinkware',family:'artifact',shape:'crystal',material:'metallic',rarity:'Common',priceUsd:'45',sourceName:'Stanley 1913',sourceUrl:'https://www.stanley1913.com/products/adventure-quencher-travel-tumbler-40-oz',previewUri:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/WaterBottle/glTF-Binary/WaterBottle.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'ikea-rosentorp-chair',name:'ROSENTORP Chair',creator:'IKEA',type:'Furniture',family:'artifact',shape:'villa',material:'wood',rarity:'Common',priceUsd:'199',sourceName:'IKEA US',sourceUrl:'https://www.ikea.com/us/en/search/?q=ROSENTORP',previewUri:'https://images.unsplash.com/photo-1503602642458-232111445657?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/SheenChair/glTF-Binary/SheenChair.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'canon-eos-r50',name:'Canon EOS R50',creator:'Canon',type:'Camera',family:'artifact',shape:'jewelry',material:'metallic',rarity:'Rare',priceUsd:'679',sourceName:'Canon USA',sourceUrl:'https://www.usa.canon.com/shop/p/eos-r50',previewUri:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/AntiqueCamera/glTF-Binary/AntiqueCamera.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'sony-wh1000xm5',name:'Sony WH-1000XM5',creator:'Sony',type:'Audio',family:'artifact',shape:'robot',material:'ceramic',rarity:'Rare',priceUsd:'399',sourceName:'Sony Electronics US',sourceUrl:'https://electronics.sony.com/audio/headphones/headband/p/wh1000xm5-b',previewUri:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/Sunglasses/glTF-Binary/Sunglasses.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'rayban-wayfarer-rb2140',name:'Ray-Ban Original Wayfarer',creator:'Ray-Ban',type:'Eyewear',family:'artifact',shape:'jewelry',material:'glass',rarity:'Rare',priceUsd:'196',sourceName:'Ray-Ban',sourceUrl:'https://www.ray-ban.com/usa/sunglasses/original-wayfarer',previewUri:'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/Sunglasses/glTF-Binary/Sunglasses.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'lego-mclaren-mcl39',name:'LEGO Technic McLaren Formula 1',creator:'LEGO',type:'Collectible Model',family:'vehicle',shape:'car',material:'plastic',rarity:'Epic',priceUsd:'229.99',sourceName:'LEGO Shop US',sourceUrl:'https://www.lego.com/en-us/product/mclaren-mcl39-f1-car-42228',previewUri:'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/ToyCar/glTF-Binary/ToyCar.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'nike-air-force-1-07',name:'Nike Air Force 1 07',creator:'Nike',type:'Footwear',family:'artifact',shape:'fox',material:'leather',rarity:'Rare',priceUsd:'115',sourceName:'Nike',sourceUrl:'https://www.nike.com/t/air-force-1-07-mens-shoes',previewUri:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/Shoe/glTF-Binary/Shoe.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'logitech-mx-keys-s',name:'Logitech MX Keys S',creator:'Logitech',type:'Keyboard',family:'artifact',shape:'robot',material:'metallic',rarity:'Uncommon',priceUsd:'109',sourceName:'Logitech',sourceUrl:'https://www.logitech.com/en-us/products/keyboards/mx-keys-s.html',previewUri:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/Box/glTF-Binary/Box.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'trek-marlin-7',name:'Trek Marlin 7',creator:'Trek',type:'Bicycle',family:'vehicle',shape:'motorcycle',material:'metallic',rarity:'Epic',priceUsd:'999',sourceName:'Trek',sourceUrl:'https://www.trekbikes.com/us/en_US/bikes/mountain-bikes/cross-country-mountain-bikes/marlin/marlin-7-gen-3/p/5308054/',previewUri:'https://images.unsplash.com/photo-1485965120184-e220f721d03e?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/ToyCar/glTF-Binary/ToyCar.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'fellow-stagg-ekg',name:'Fellow Stagg EKG Electric Kettle',creator:'Fellow',type:'Kitchen',family:'artifact',shape:'crystal',material:'metallic',rarity:'Rare',priceUsd:'195',sourceName:'Fellow',sourceUrl:'https://fellowproducts.com/products/stagg-ekg-electric-kettle',previewUri:'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/WaterBottle/glTF-Binary/WaterBottle.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'},
{id:'rayban-meta-wayfarer',name:'Ray-Ban Meta Wayfarer',creator:'Ray-Ban Meta',type:'Smart Eyewear',family:'artifact',shape:'jewelry',material:'glass',rarity:'Legendary',priceUsd:'379',sourceName:'Ray-Ban Meta',sourceUrl:'https://www.ray-ban.com/usa/discover-ray-ban-meta',previewUri:'https://images.unsplash.com/photo-1577803645773-f96470509666?auto=format&fit=crop&w=1200&q=85',modelUri:`${MODEL_BASE}/Sunglasses/glTF-Binary/Sunglasses.glb`,modelSource:'Khronos glTF Sample Assets',modelLicense:'CC BY 4.0',modelStatus:'3D REFERENCE'}
];

export const REAL_WORLD_CATALOG=items.map((item,index)=>({...item,id:item.id||`real-object-${index+1}`,price:item.priceUsd,blocks:'Verified source',color:'violet',variant:'real-world reference',inspiration:item.name,physicalSource:item.sourceUrl,digitalTwin:{modelUrl:item.modelUri,previewUrl:item.previewUri,source:item.modelSource,license:item.modelLicense,status:item.modelStatus},isRealWorld:true,isSynthetic:false,sourceVerified:Boolean(item.sourceUrl),renderMode:'remote3d',seed:`real-${item.id}`}));
export const getRealWorldCatalog=()=>REAL_WORLD_CATALOG.slice();
