'use client';

import { useState } from 'react';
import Link from 'next/link';

export default function IntelligenceLab() {
  const [query, setQuery] = useState('What are the newest developments in quantum computing and digital collectibles?');
  const [answer, setAnswer] = useState('');
  const [loading, setLoading] = useState(false);
  const [quantum, setQuantum] = useState(null);
  const research = async () => {
    setLoading(true); setAnswer('');
    try { const r = await fetch('/api/ai/research', { method:'POST', headers:{'content-type':'application/json'}, body:JSON.stringify({query}) }); const d=await r.json(); setAnswer(d.answer || d.error || 'No result.'); }
    catch { setAnswer('Research service unavailable.'); } finally { setLoading(false); }
  };
  const runQuantum = async () => { const r=await fetch('/api/quantum/simulate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({experiment:'bell'})}); setQuantum(await r.json()); };
  return <main className="page"><header><Link href="/">‹ Vault</Link><div><small>VOXEL VAULT</small><h1>Intelligence Lab</h1></div><span>AI · Q</span></header>
    <section className="hero"><small>LIVE KNOWLEDGE + COMPUTATION</small><h2>Ask the web.<br/><em>Explore the universe.</em></h2><p>AI research can use current web information. The quantum lab runs safe local simulations until real quantum hardware credentials are configured.</p></section>
    <section className="card"><label>AI RESEARCH</label><textarea value={query} onChange={e=>setQuery(e.target.value)} maxLength={1200}/><button onClick={research} disabled={loading}>{loading?'Researching…':'Research current information →'}</button>{answer&&<article className="answer">{answer}</article>}</section>
    <section className="card quantum"><label>QUANTUM LAB</label><h3>Bell-state experiment</h3><p>Create a two-qubit entangled state in a classical statevector simulator and inspect the measurement probabilities.</p><button onClick={runQuantum}>Run experiment</button>{quantum?.states&&<div className="states">{quantum.states.map(s=><div key={s.basis}><span>|{s.basis}⟩</span><b>{(s.probability*100).toFixed(1)}%</b><i><u style={{width:`${s.probability*100}%`}}/></i></div>)}</div>}{quantum?.note&&<small className="note">{quantum.note}</small>}</section>
    <section className="card"><label>VOXEL AI ENGINE</label><div className="chips"><span>🌐 Web research</span><span>🧠 Asset intelligence</span><span>🧊 3D generation</span><span>⚛️ Quantum simulation</span><span>🔗 Provenance analysis</span><span>🛡️ Safety gates</span></div></section>
    <footer><Link href="/">Find</Link><Link href="/receipt">Scan</Link><Link href="/room">Vault</Link></footer>
    <style jsx>{`.page{min-height:100vh;background:#05060b;color:#f6f7fb;padding:0 16px 38px;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.page header{height:70px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(255,255,255,.08)}header a{color:#fff;text-decoration:none;font-size:10px}header>span{font-size:9px;color:#8d7fff}header div{text-align:center}header small,.card>label,.hero>small{font-size:7px;letter-spacing:.17em;color:#9d8cff;font-weight:900}h1{font-size:18px;margin:4px 0}.hero{padding:32px 0 18px}.hero h2{font-size:39px;line-height:.93;letter-spacing:-.06em;margin:9px 0}.hero em{font-style:normal;color:#a894ff}.hero p,.card p{font-size:10px;line-height:1.55;color:#7e889b}.card{border:1px solid rgba(255,255,255,.09);border-radius:21px;background:rgba(255,255,255,.035);padding:17px;margin-bottom:11px}.card textarea{display:block;width:100%;min-height:110px;margin:10px 0;padding:12px;border-radius:13px;border:1px solid rgba(255,255,255,.08);background:#080a11;color:#eef1f7;resize:vertical;outline:none;font:12px/1.45 inherit}.card button{width:100%;border:0;border-radius:13px;padding:13px;background:#f5f6f9;color:#08090d;font-weight:900;font-size:10px}.card button:disabled{opacity:.5}.answer{white-space:pre-wrap;margin-top:12px;padding:13px;border-radius:14px;background:#080a11;border:1px solid rgba(255,255,255,.07);font-size:10px;line-height:1.6;color:#cbd1dd;max-height:480px;overflow:auto}.quantum h3{font-size:18px;margin:8px 0}.states{margin-top:14px;display:grid;gap:10px}.states>div{display:grid;grid-template-columns:50px 48px 1fr;align-items:center;gap:8px;font-size:10px}.states b{text-align:right}.states i{height:7px;border-radius:99px;background:#151823;overflow:hidden}.states u{display:block;height:100%;background:linear-gradient(90deg,#806cff,#5ce1ff);border-radius:99px;text-decoration:none}.note{display:block;margin-top:10px;color:#667084;font-size:8px;line-height:1.4}.chips{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}.chips span{padding:8px 9px;border:1px solid rgba(255,255,255,.08);border-radius:999px;color:#cbd1dc;font-size:8px}footer{display:flex;justify-content:center;gap:22px;margin-top:20px}footer a{color:#687184;text-decoration:none;font-size:9px}@media(min-width:700px){.page{max-width:680px;margin:auto}}`}</style>
  </main>;
}
